### ISSUE TITLE
Incoming connections is always 0 after moved to a new place(IP changed)

### ISSUE THREAD

**Issue by Lizliu1991** [pi-node/instructions#153]
Hey team,

After I moved to a new place, my incoming connections is always 0, and I confirmed that the router is correctly configured. The only changed thing is my public IP address.
<img width="587" alt="Screen Shot 2021-07-13 at 9 51 47 pm" src="https://user-images.githubusercontent.com/69944703/125447467-fcf938ac-c0a4-4876-9554-dd6605a09be7.png">

**Comment by ihatejam** [comment]
Your node seems to be syncing so that part is fine...
While the Pi app is in the current state, visit https://www.ipfingerprints.com/portscan.php from a browser.
Set the start port = 31400 and the end port = 31409 and then perform a scan.
Do ports 31401 to 31403 report as open while the rest show up as close or filtered?

**Comment by Lizliu1991** [comment]
> Your node seems to be syncing so that part is fine...
> While the Pi app is in the current state, visit https://www.ipfingerprints.com/portscan.php from a browser.
> Set the start port = 31400 and the end port = 31409 and then perform a scan.
> Do ports 31401 to 31403 report as open while the rest show up as close or filtered?

Below is the result:
31400/tcp filtered pace-licensed
31401/tcp filtered unknown
31402/tcp filtered unknown
31403/tcp filtered unknown
31404/tcp filtered unknown
31405/tcp filtered unknown
31406/tcp filtered unknown
31407/tcp filtered unknown
31408/tcp filtered unknown
31409/tcp filtered unknown

I think it's port not open but I did config Mac firewall to "Allow incoming connections" for docker app and correctly set up the port forwarding in router, not sure how to fix.

**Comment by ihatejam** [comment]
I suspect that your internet router at your new location has not been configured to forward traffic on those ports to your node PC.

**Comment by Lizliu1991** [comment]
> I suspect that your internet router at your new location has not been configured to forward traffic on those ports to your node PC.

Quite possible, if I use my another laptop to ping this pi-node machine's internal ip address, looks like port 31400-31403 is open
![Screen Shot 2021-07-15 at 3 50 30 pm](https://user-images.githubusercontent.com/69944703/125735878-c7213f7e-c11f-4a2c-857a-3a6a9f6fed44.png)

**Comment by ihatejam** [comment]
If you haven't manually configured port forwarding on the router at your new location, then that would be the problem. Other nodes (since they are external to your local network) cannot communicate with your node.

You would need to log into the internet router and configure port forwarding to get it to work.

**Comment by Lizliu1991** [comment]
> If you haven't manually configured port forwarding on the router at your new location, then that would be the problem. Other nodes (since they are external to your local network) cannot communicate with your node.
> 
> You would need to log into the internet router and configure port forwarding to get it to work.

Thank you, finally found the issue, I just bought a static public ip address and now it's working well.
