### ISSUE TITLE
Pi Node - The ports are not opening in Windows 11

### ISSUE THREAD

**Issue by Spacewarrior17** [pi-node/instructions#237]
Please guide me how to make it open in windows 11.
Also, the Ports are running but not connecting to external ports.

**Comment by ihatejam** [comment]
Hi,

1) Have you configured the port forwarding in your router admin interface?
2) Have you allowed those ports through your Windows firewall?
3) Once 1 and 2 are done - please retest port forwarding while the "Stellar Dummy" container is running in Docker. Double check port forwarding with https://www.ipfingerprints.com/portscan.php  (if you decide to post a screenshot of the port forwarding results, please hide your IP address).

There are cases, where port forwarding will not work -- the most common is if your ISP does not hand out "real" IP addresses. This is commonly the case with ISP's who have more customers to serve than the IP addresses they've been allocated. This is also the case with internet via mobile phone or using internet provided over 4G/5G. If this is the case, you will not be able to get port forwarding working without using a VPN service that supports port forwarding.

**Comment by Spacewarrior17** [comment]
Yes, I have already done those things, I tried to check the port testing link you have shared. It says "Filtered" packet filtering through eg., Firewall.
But I have already set up the inbound rule.
What's the problem?
I will be sending a screenshot of inbound rule.
Is there any problem with docker? Or it's my router?
Or I'm doing something wrong myself?

![IMG_20220210_215524.jpg](https://user-images.githubusercontent.com/82926318/153452271-d678a67f-bfab-456d-bc26-ff230ed9ba40.jpg)

![IMG_20220210_215658.jpg](https://user-images.githubusercontent.com/82926318/153452324-3e9d1fa0-1ce9-48af-a970-a6d40354c55f.jpg)

**Comment by Spacewarrior17** [comment]
Here are other screenshots to look on

Is there a problem with Docker actually?

![IMG20220210220520.jpg](https://user-images.githubusercontent.com/82926318/153453743-5e294a17-11d5-4016-85b8-95bc803c567d.jpg)

![IMG_20220210_220750.jpg](https://user-images.githubusercontent.com/82926318/153453776-eb0e8b41-41d0-43ec-83c2-e28c4003b4fe.jpg)

**Comment by Spacewarrior17** [comment]
Hey, is there an issue with this?
The port is listening but there is a 3 set of ports from 31400 to 31409.
This isn't normal, is it?

1.
![IMG_20220210_221820.jpg](https://user-images.githubusercontent.com/82926318/153456418-a73bacc9-acc8-4657-a7a9-cd155a4e2194.jpg)

2.
![IMG_20220210_221925.jpg](https://user-images.githubusercontent.com/82926318/153456464-22d22079-e550-481c-8890-690aea117099.jpg)

3.
![IMG_20220210_222028.jpg](https://user-images.githubusercontent.com/82926318/153456483-74902307-0eae-4789-88ec-a632b2428b64.jpg)

**Comment by ihatejam** [comment]
your config looks fine - (although I can't see the content of your firewall rules). The reason you see the ports listed 3 times seems to be because you have both ipv4 and ipv6 enabled (ipv6 is prefixed with [::] and [::1] in this case). Having ipv6 on is not a problem though, but you can turn it off if you don't need it (also the node only uses ipv4 at the moment).

On ipfingerprint, you are only checking the first the first port -- please check the others. I set the range to include 31400 to 31409 like this:-
![image](https://user-images.githubusercontent.com/17174125/153466409-6e518e1a-eadb-4365-99a6-1c48420dac85.png)

If ipfingerprints can reach the ports on your nodes listener, then you should see entries like this for all ports
![image](https://user-images.githubusercontent.com/17174125/153466629-c56285cf-3680-465b-862a-49d53fc2424d.png)

If you are not seeing the ports open, then chances are that your ISP does not allow port forwarding. A further check would be to see if the IP address of your router's WAN adapter (in the admin interface) matches the IP address that ipfingerprints thinks you are accessing the internet from. (Note I am talking about your WAN adapter's ISP assigned IP address and not anything on the LAN side). 
If the IP address on the WAN adapter matches the IP address listed on ipfingerprints, then it may still be a local configuration issue that you can fix. 
If the two IP addresses are different, then your ISP is using an internal NAT and not providing you with a "real" public IP address -- which means you cannot configure port forwarding. The options would be to move to a different provider that supports port forwarding or to use a VPN service that offers port forwarding. Even though it is not listed as a service, I have successfully used Surfshark in the past to keep my node working while I was traveling. (Of course, Pi Network does not endorse any particular VPN service, so it would be for you to test and decide which one you would like to use)

Hope this helps...

**Comment by Spacewarrior17** [comment]
Thank you very much, I think I now know the solution.

I should probably use a vpn cause for the time being I can't change the wifi provider.
