### ISSUE TITLE
Hardware requirements & Power options?

### ISSUE THREAD

**Issue by lavrentius-dev** [pi-node/instructions#72]
I can't seem to find the minimal/default hardware requirements (min HDD/SSD size, RAM, CPU, UPS, Internet bandwidth) in the documentation. These are important things to know before setting up the node.

Running the machine 24/7 when there is no node workload increases the risk of wear and tear with no perceived benefit when compared to other Pi network users who do not run nodes. There is no formal agreement and no incentive provided for users to run a node. To minimize this risk, it would make sense to enable computer sleep while there is no node workload. I enabled WOL on the NIC and the PC wakes up from sleep when receiving incoming connections on ports 3140* of the router's external IP.

Can anybody confirm if this configuration is compatible with the requirements to run a Pi node?

**Comment by ihatejam** [comment]
Right now, the Pi team are running a test blockchain, so there is no formal agreement nor any incentive.
Here's my understanding of running the node app... 
In order to enroll you as a node vs a supernode, the Pi team use your availability stats in the Pi app to determine your suitability for either node type. The idea is that you should let your node run as you intend to do when everything is up and running, so that your commitment can be gauged (while this is not exactly eco-friendly, it is the only way to check out people's actual participation capability) -- so having your pc on sleep will not reflect the hours you intend to run your node correctly.

**Comment by ihatejam** [comment]
more info by the Pi team can be found here - https://minepi.com/node-info

**Comment by lehboi** [comment]
I have been running Pi Node for a week.
Currently, there is not much work, so a CPU Intel core i3 2348M is more than enough. It works on average 20% CPU load. I set my computer in Power saver plan to reduce heat.
You cannot let your computer sleep because connections in and out continuously every second. Every day it sends and receives around 1GB.
The disk space used by the database at this time is under 200MB.

**Comment by t4ndu** [comment]
> Right now, the Pi team are running a test blockchain, so there is no formal agreement nor any incentive.
> Here's my understanding of running the node app...
> In order to enroll you as a node vs a supernode, the Pi team use your availability stats in the Pi app to determine your suitability for either node type. The idea is that you should let your node run as you intend to do when everything is up and running, so that your commitment can be gauged (while this is not exactly eco-friendly, it is the only way to check out people's actual participation capability) -- so having your pc on sleep will not reflect the hours you intend to run your node correctly.

- but if we want to run linux servers - and not want to let run or laptops.. you cant find the one for linux servers to see where are the supernodes... is unlogical. make a server version the let it run on a VPS and make a shell script for intsall the Pi node there. an give the ufw parameters to enable the firewall.. make an simple config file to connect pi node with pi app... and all ist good. its so easy.

**Comment by Adeday0** [comment]
There should be proper information on how setting up the node is going to be. The docker app has transmitted about 12GB of data in the last 3 hours and the setup is still not done yet. How does this even make sense??

**Comment by plandregan** [comment]
I had this running for around 12hr on a debian machine.
I allocated 4gb of ram and 64gb of ssd space.

It consumed the entire drive and crashed.
 How much space does this actually need?

**Comment by Nucleoo07** [comment]
To use pi node and get good rewards in return use i5 min 8 th gen ( i 7 even better )  - RAM -16 Gb - SSd 256 gb NVME ( 500 Gb better )
GFX - no need - **stable internet no lags 24 x7 -   1 pi account = 1 pi node . 1 internet connection = 1 pi node .  PI REWARDS - 5.1 -6 .5   Depending on your uptime .**
