### ISSUE TITLE
Waiting for postgres to be available...

### ISSUE THREAD

**Issue by nicolae788** [pi-node/instructions#78]
Diagnostics Info
Container
Consensus container enabled: Yes

Node switch on: Yes

PortsChecker container: exited

Consensus container: running

Consensus
State: N/A

Protocol version: N/A

Latest block: N/A

Outgoing connections: N/A

Incoming connections: N/A

Supporting other nodes: No

Other
Pi Node version number: 0.4.3

Operating system: WINDOWS 10.0.17763 (Microsoft Windows Server 2019 Datacenter Evaluation)

Using Docker Toolbox: No

Node installation date: 2021-02-24

Availability (up to 90 days): 63.51% from 2021-02-24 to 2021-02-26

**Above you have the details from the PI desktop client. The consensus container just got downloaded today about 3 hours ago. Is this message a normal situation?**

Waiting for postgres to be available...

Waiting for postgres to be available...

Waiting for postgres to be available...

Waiting for postgres to be available...

Waiting for postgres to be available...

Waiting for postgres to be available...

Waiting for postgres to be available...

Waiting for postgres to be available...

Waiting for postgres to be available...

Thank you !

**Comment by ihatejam** [comment]
There are rare cases where it can get stuck here - but it does also take a while for it to get the postgres db going - which is what could be happening here. Leave it running in the current state to do its thing for now and check back tomorrow.

**Comment by nicolae788** [comment]
Ok, thank you for the heads up. Will get back with news, when they will be !

**Comment by nicolae788** [comment]
8 days later and 89.68% availability still the same ' waiting for postgres to be available'. Is this normal? ...looks like it's a dry run or something. Processor usage for the consensus container it's steady somwhere around 25-30% and in top i can see psql command executed repeatedly by user postgres, and sometimes command ldd by same user, postgres

**Comment by ihatejam** [comment]
Hi. This is unexpected. It should not take this long to get going.

What version of docker desktop are you running? I think a few updates have just been posted. 

When you right-click on the docker icon in the windows system tray, do you have a switch that says "Switch to Windows containers" or does it say "Switch to Linux containers"? It toggles from one to the other when you select it. These are Linux containers, so the switch should always read "switch to Windows containers" but I would like you to toggle to Windows containers and then back, so that the switch once again reads "switch to Windows containers". Short of recreating the container, I think there is some odd permissions issue coming into play here.

You could also try turning off the node switch in the node app and then using "Remove blockchain data" under the troubleshooting menu to see if starting afresh works.

If this fails, try to get the attention of the moderators in the Node chat room in the pi mobile app - they may be able to help some more. (You can now post screenshots in there).

**Comment by nicolae788** [comment]
Ok. Long story short, i was running the latest docker, with the right settings, under Windows Server 2019 with Hyper-V. Something was not right for multiple reasons, all of them lying in the OS part of the contraption. And since the server was a VM, i decided to wipe it and install a Windows10 Pro.

I backed up the "Pi Network" folder so i will not loose the progress with the blockchain. Then i installed a fresh Windows10 Pro VM, updated, fine tuning and followed the instructions from " https://github.com/pi-node/instructions/wiki/(EN)-New-instructions-for-docker-desktop-with-wsl2-(windows-2004) ". Last i installed the Pi Node app for desktop and after installing it, i copied over the saved files from the former installation overwriting the existent ones.

With Docker running, i started Pi and immediately the consensus container appeared, started and  no more problems. Except that it reports the ports checker as absent, but this is not a problem. 

So, problem solved. 

Thank you for your support and hints, Ihatejam :)

**Comment by ihatejam** [comment]
My bad - I completely missed that part about windows server in your first post!!!
